Update to resolve issue 99
dunglas/doctrine-json-odm pull request #100
Opened 2021-12-29 23:16 UTC by joseenriquevasquez

https://github.com/dunglas/doctrine-json-odm/issues/99

2021-12-30 09:33 UTC, dunglas requested changes

2021-12-30 09:33 UTC, dunglas commented on composer.json
> +  "name": "joseenriquevasquez/doctrine-json-odm",
To be reverted.

2021-12-30 09:33 UTC, dunglas commented on src/Serializer.php
> +    public function normalize($data, $format = null, array $context = []):array
```suggestion
    public function normalize($data, $format = null, array $context = []): array
```

2021-12-30 09:33 UTC, dunglas commented on src/Serializer.php
> +    public function denormalize($data, $class, $format = null, array $context = []):array
```suggestion
    public function denormalize($data, $class, $format = null, array $context = []): array
```

2022-01-17 17:00 UTC, ddeboer commented
Opened a new PR #102 to speed things up a bit.

2022-01-19 21:07 UTC, dunglas commented
Closing in favor of #102

2022-01-19 21:07 UTC, closed without merging