Fix denormalizing enums
dunglas/doctrine-json-odm pull request #114
Opened 2022-03-10 12:19 UTC by norkunas

Closes #113

2022-03-10 23:28 UTC, dunglas approved these changes

2022-04-01 08:30 UTC, norkunas commented
Will this be merged? :)

2022-06-15 13:55 UTC, norkunas commented
friendly ping @dunglas :)

2022-06-15 15:22 UTC, dunglas requested changes
Could you also apply the StyleCI patch please?

2022-06-15 15:22 UTC, dunglas commented on src/Bundle/DependencyInjection/DunglasDoctrineJsonOdmExtension.php
> +        if (!class_exists(BackedEnumNormalizer::class)) {
You should also call `removeDefinition` if `\BackedEnum` doesn't exist because the class can exist even with old PHP versions (Symfony 5.4).

2022-06-15 20:29 UTC, merged

2022-06-15 20:29 UTC, dunglas commented
Thanks!

2022-09-08 09:38 UTC, darthf1 commented
Would it be possible to push a new release with this change? :)